{
  "openapi": "3.0.0",
  "info": {
    "version": "0.0.1",
    "title": "API - Protótipo (App Operacional)"
  },
  "servers": [
    {
      "url": "operacionalapp.heroku.com"
    }
  ],
  "tags": [
    {
      "name": "Ativação"
    },
    {
      "name": "Autenticação"
    },
    {
      "name": "Assinante"
    },
    {
      "name": "Funcionário"
    },
    {
      "name": "Loja"
    },
    {
      "name": "Inventário"
    },
    {
      "name": "Unidade"
    },
    {
      "name": "Produto"
    },
    {
      "name": "Menu"
    }
  ],
  "paths": {
    "/ativacao": {
      "post": {
        "tags": [
          "Ativação"
        ],
        "summary": "Ativar o App",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AtivacaoModel"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseModel"
                },
                "example": {
                  "message": "Dispositivo ativado com sucesso"
                }
              }
            }
          }
        }
      }
    },
    "/auth": {
      "post": {
        "tags": [
          "Autenticação"
        ],
        "summary": "Iniciar uma sessão no App",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AuthModel"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuthModel"
                }
              }
            }
          }
        }
      }
    },
    "/assinante": {
      "post": {
        "tags": [
          "Assinante"
        ],
        "summary": "Informações da assinatura",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AssinanteModel"
                }
              }
            }
          }
        }
      }
    },
    "/auth/refresh": {
      "post": {
        "tags": [
          "Autenticação"
        ],
        "summary": "Atualizar a sessão",
        "operationId": "authRefresh",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "Enviar o token_refresh",
            "schema": {
              "type": "string",
              "example": "1as6d8a4sd8as4d64as8d4as3d48a6s4dasd86a7sd54as6d8a4s"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuthModel"
                }
              }
            }
          }
        }
      }
    },
    "/auth/logout": {
      "post": {
        "tags": [
          "Autenticação"
        ],
        "summary": "Encerrar sessão",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "Enviar o access_token",
            "schema": {
              "type": "string",
              "example": "a9s87da87sd89a7sd7a89s7da89s7d0897as89da0s987"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponseModel"
                },
                "example": {
                  "message": "Dispositivo ativado com sucesso"
                }
              }
            }
          }
        }
      }
    },
    "/funcionario": {
      "get": {
        "tags": [
          "Funcionário"
        ],
        "summary": "Retorna os dados do usuário logado",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "Enviar o access_token",
            "schema": {
              "type": "string",
              "example": "a9s87da87sd89a7sd7a89s7da89s7d0897as89da0s987"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/FuncionarioModel"
                },
                "examples": {
                  "funcionario": {
                    "$ref": "#/components/examples/funcionario"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/inventario": {
      "get": {
        "tags": [
          "Inventário"
        ],
        "summary": "Lista todos os inventários abertos das lojas que o usuário possui acesso",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "Enviar o access_token",
            "schema": {
              "type": "string",
              "example": "a9s87da87sd89a7sd7a89s7da89s7d0897as89da0s987"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/InventarioModel"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/loja": {
      "get": {
        "tags": [
          "Loja"
        ],
        "summary": "Retorna a lista de todas as lojas que o usuário tem acesso",
        "operationId": "loja",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "Enviar o access_token",
            "schema": {
              "type": "string",
              "example": "a9s87da87sd89a7sd7a89s7da89s7d0897as89da0s987"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/LojaModel"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/loja/{id}/inventario": {
      "get": {
        "tags": [
          "Loja"
        ],
        "summary": "Retorna todos os inventarios filtrando pela loja",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "Enviar o access_token",
            "schema": {
              "type": "string",
              "example": "a9s87da87sd89a7sd7a89s7da89s7d0897as89da0s987"
            }
          },
          {
            "in": "path",
            "name": "id",
            "schema": {
              "type": "integer"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/LojaModel"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/produto": {
      "get": {
        "tags": [
          "Produto"
        ],
        "summary": "Retorna todos os produtos cadastrados nas lojas",
        "operationId": "produto",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "Enviar o access_token",
            "schema": {
              "type": "string",
              "example": "a9s87da87sd89a7sd7a89s7da89s7d0897as89da0s987"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ProdutoModel"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/unidade": {
      "get": {
        "tags": [
          "Unidade"
        ],
        "summary": "Retorna a lista de todas as unidades",
        "operationId": "unidade",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "Enviar o access_token",
            "schema": {
              "type": "string",
              "example": "a9s87da87sd89a7sd7a89s7da89s7d0897as89da0s987"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/UnidadeModel"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/menu": {
      "get": {
        "tags": [
          "Menu"
        ],
        "summary": "Retorna os menus que o usuário possui acesso filtrando com base nas suas permissões",
        "operationId": "menu",
        "parameters": [
          {
            "in": "header",
            "name": "Authorization",
            "required": true,
            "description": "Enviar o access_token",
            "schema": {
              "type": "string",
              "example": "a9s87da87sd89a7sd7a89s7da89s7d0897as89da0s987"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/MenuModel"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "examples": {
      "lojas": {
        "value": {
          "id": 1,
          "nome_fantasia": "SUPERMERCADO SIMARA LTDA",
          "endereco": "RUA EXP. ANTONIO CAETANO DE SOUZA FILHO 789",
          "logo": "https://operacional.herokuapp.com/images/loja1.jpg",
          "configuracao_produto": {
            "qtd_digito_produto_peso": 4,
            "qtd_decimal_etiqueta_peso": 3
          }
        }
      },
      "funcionario": {
        "value": {
          "nome": "Marina",
          "sobrenome": "Gosson",
          "telefone": "85986280030",
          "username": "marinagosson",
          "email": "marina.gosson@gmail.com",
          "administrador": false
        }
      },
      "menu": {
        "value": {
          "titulo": "Controle de estoque",
          "subtitulo": "Contagem de produto",
          "descricao": null,
          "ordem": 1,
          "parent": 1,
          "permissoes": {
            "type": "array",
            "items": {
              "example": "EDITAR",
              "enum": [
                "EDITAR",
                "EXCLUIR",
                "ADICIONAR"
              ]
            }
          }
        }
      }
    },
    "schemas": {
      "InventarioModel": {
        "type": "object",
        "properties": {
          "storeId": {
            "type": "integer"
          },
          "ultima_contagem": {
            "type": "integer"
          },
          "descricao": {
            "type": "integer"
          },
          "observacao": {
            "type": "integer"
          },
          "tipo_contagem": {
            "type": "string",
            "enum": [
              "SIMPLES"
            ]
          },
          "permite_produto_avulso": {
            "type": "boolean",
            "example": true
          },
          "produtos": {
            "type": "array",
            "items": {
              "type": "integer",
              "format": "int64"
            },
            "example": [
              4648,
              7891681385695,
              5686
            ]
          },
          "contagem_iniciada": {
            "type": "boolean"
          }
        }
      },
      "MenuModel": {
        "type": "object",
        "properties": {
          "titulo": {
            "type": "string",
            "example": "Controle de estoque"
          },
          "subtitulo": {
            "type": "string",
            "example": "Contagem de produto"
          },
          "descricao": {
            "type": "string",
            "example": null
          },
          "ordem": {
            "type": "integer",
            "example": 1
          },
          "parent": {
            "type": "integer",
            "example": null
          },
          "permissoes": {
            "type": "array",
            "items": {
              "type": "string",
              "example": null,
              "enum": [
                "EDITAR",
                "EXCLUIR",
                "ADICIONAR"
              ]
            }
          },
          "submenu": {
            "type": "array",
            "items": {
              "allOf": [
                {
                  "type": "object"
                },
                {
                  "$ref": "#/components/schemas/MenuModel"
                }
              ],
              "example": {
                "titulo": "Inventário de Produtos",
                "subtitulo": "Lorem impsum",
                "descricao": null,
                "ordem": 1,
                "parent": 1,
                "permissoes": [
                  "LISTAR INVENTARIOS",
                  "NOVA CONTAGEM",
                  "EXCLUIR CONTAGEM",
                  "EDITAR CONTAGEM"
                ],
                "submenu": null
              }
            }
          }
        }
      },
      "ApiResponseModel": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        }
      },
      "LojaModel": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "example": 1
          },
          "nome_fantasia": {
            "type": "string",
            "example": "SUPERMERCADO SIMARA LTDA"
          },
          "endereco": {
            "type": "string",
            "example": "RUA EXP. ANTONIO CAETANO DE SOUZA FILHO 789"
          },
          "logo": {
            "type": "string",
            "example": "https://operacional.herokuapp.com/images/loja1.jpg"
          },
          "configuracao_produto": {
            "$ref": "#/components/schemas/ConfiguracaoProdutoModel"
          }
        }
      },
      "ConfiguracaoProdutoModel": {
        "type": "object",
        "properties": {
          "qtd_digito_produto_peso": {
            "type": "integer",
            "example": 4
          },
          "qtd_decimal_etiqueta_peso": {
            "type": "integer",
            "example": 3
          }
        }
      },
      "AuthModel": {
        "type": "object",
        "required": [
          "access_token",
          "token_refresh"
        ],
        "properties": {
          "access_token": {
            "type": "string",
            "example": "as0d97f0asdnf9821n98xn3284nc9821n3498n12381238c41h23984"
          },
          "token_refresh": {
            "type": "string",
            "example": "f7ua0s9d87f9as7d0fnas9d8fasnbkjbj1hvkj23v41b23l4jb3k2j1b4lkjb123lk4jbl123h4bl12k3b4li"
          }
        }
      },
      "AssinanteModel": {
        "type": "object",
        "properties": {
          "cnpj": {
            "type": "string",
            "example": "Supermercado Frangolandia"
          },
          "ativo": {
            "type": "boolean",
            "example": true
          },
          "tipos_preco": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/TipoPrecoModel"
            }
          }
        }
      },
      "ProdutoModel": {
        "type": "object",
        "required": [
          "created_at",
          "updated_at",
          "assinanteId",
          "produtoId",
          "produtoCodigo",
          "descricao",
          "ativo",
          "novo",
          "balanca",
          "quantidadeEmbalagens",
          "quantidadeItensEmbalagens",
          "unidadeVenda",
          "tipoVenda",
          "pesoVariavel",
          "codigoAuxiliares",
          "preco",
          "preco_praticado",
          "precos"
        ],
        "properties": {
          "created_at": {
            "type": "string",
            "example": "2020-02-03 13:56:52"
          },
          "updated_at": {
            "type": "string",
            "example": "2020-02-03 13:56:52"
          },
          "assinante": {
            "type": "integer"
          },
          "produtoId": {
            "type": "integer",
            "example": 123
          },
          "produtoCodigo": {
            "type": "integer",
            "example": 786
          },
          "descricao": {
            "type": "string",
            "example": "CERV EISENBAHN OKTOBER LN 355ML"
          },
          "ativo": {
            "type": "boolean",
            "example": false
          },
          "novo": {
            "type": "boolean",
            "example": false
          },
          "balanca": {
            "type": "boolean",
            "example": false
          },
          "quantidadeEmbalagens": {
            "type": "number",
            "format": "double",
            "example": 1
          },
          "quantidadeItensEmbalagens": {
            "type": "number",
            "format": "double",
            "example": 1
          },
          "unidadeVenda": {
            "type": "string",
            "example": "UN"
          },
          "tipoVenda": {
            "type": "string",
            "example": null
          },
          "pesoVariavel": {
            "type": "string",
            "example": "N"
          },
          "codigos_axiliares": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/CodigoAuxiliarModel"
            }
          },
          "precos": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PrecoModel"
            }
          },
          "preco_praticado": {
            "type": "number",
            "format": "double",
            "example": 12.30
          }
        }
      },
      "PrecoModel": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "example": 123456
          },
          "created_at": {
            "type": "string",
            "example": "2020-02-03T13:56:52.000Z"
          },
          "updated_at": {
            "type": "string",
            "example": "2020-02-03T13:56:52.000Z"
          },
          "loja_id": {
            "type": "integer",
            "example": 56
          },
          "produto_id": {
            "type": "integer",
            "example": 56
          },
          "tipo_preco_id": {
            "type": "integer",
            "example": 1
          },
          "valor_oferta": {
            "type": "number",
            "format": "double",
            "example": 12.3
          },
          "valor_venda": {
            "type": "number",
            "format": "double"
          },
          "oferta": {
            "type": "boolean",
            "example": true
          },
          "venda": {
            "type": "boolean",
            "example": false
          }
        }
      },
      "TipoPrecoModel": {
        "type": "object",
        "properties": {
          "descricao": {
            "type": "string",
            "example": "Atacado"
          },
          "ativo": {
            "type": "boolean",
            "example": true
          },
          "assinante_id": {
            "type": "integer",
            "example": 1
          }
        }
      },
      "CodigoAuxiliarModel": {
        "type": "object",
        "required": [
          "created_at",
          "updated_at"
        ],
        "properties": {
          "created_at": {
            "type": "string",
            "example": "2020-02-03 13:56:52"
          },
          "updated_at": {
            "type": "string",
            "example": "2020-02-03 13:56:52"
          },
          "assinante": {
            "type": "integer"
          },
          "fator": {
            "type": "integer"
          },
          "tipo": {
            "type": "string",
            "enum": [
              "EAN",
              "LITERAL"
            ],
            "example": "EAN"
          },
          "produto_codigo": {
            "type": "integer",
            "example": 1082
          },
          "codigo_ean": {
            "type": "string",
            "example": "7898367982069"
          },
          "principal": {
            "type": "boolean",
            "example": true
          }
        }
      },
      "AtivacaoModel": {
        "type": "object",
        "required": [
          "assinatura",
          "dispositivo"
        ],
        "properties": {
          "assinatura": {
            "type": "string",
            "example": "a4s86d4as1d6as4d863a74sda1sd68as1d38as4d8as"
          },
          "dispositivo": {
            "$ref": "#/components/schemas/DispositivoModel"
          }
        }
      },
      "DispositivoModel": {
        "type": "object",
        "required": [
          "so_versao",
          "so",
          "marca",
          "fabricante",
          "modelo",
          "uuid"
        ],
        "properties": {
          "so": {
            "type": "string",
            "example": "android"
          },
          "so_versao": {
            "type": "string",
            "example": "8.1.0"
          },
          "marca": {
            "type": "string",
            "example": "motorola"
          },
          "fabricante": {
            "type": "string",
            "example": "motorola"
          },
          "modelo": {
            "type": "string",
            "example": "Moto G (5) Plus"
          },
          "uuid": {
            "type": "string",
            "example": "a566a5c0-46c9-11ea-ae58-03bb3c51b6dc"
          }
        }
      },
      "UnidadeModel": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "example": 8
          },
          "assinante_id": {
            "type": "integer",
            "example": 5
          },
          "codigo": {
            "type": "string",
            "example": "UN"
          },
          "descricao": {
            "type": "string",
            "example": "Unidade"
          }
        }
      },
      "FuncionarioModel": {
        "type": "object",
        "properties": {
          "nome": {
            "type": "string"
          },
          "sobrenome": {
            "type": "string"
          },
          "telefone": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "administrador": {
            "type": "boolean"
          },
          "foto": {
            "type": "string"
          }
        }
      }
    }
  }
}